<?php
declare(strict_types=1);

/** @return array<string,array<string,mixed>> */
function recruitment_guide_manifest(): array
{
    $definitions = [
        'overview'=>['Recruitment overview','Start here','Everyone','Understand the complete hiring lifecycle and the release boundary.',['Lifecycle map'=>'See each governed stage and owner.','Release boundary'=>'Confirm whether workflows are connected.','Role paths'=>'Choose candidate or staff guidance.'],['Orient yourself','Choose your role','Open the relevant page'],['lifecycle','roles','start','governance']],
        'candidate.sign-in'=>['Candidate sign in','Candidate account','Candidates','Reach the protected candidate workspace.',['Account status'=>'Shows whether candidate identity is available.','Email and password'=>'Candidate-only credentials, separate from employee access.','Recovery link'=>'Starts the anti-enumeration recovery route.'],['Open sign in','Enter candidate credentials','Reach candidate home'],['login','candidate account','password','session']],
        'candidate.register'=>['Create candidate account','Candidate account','Candidates','Create a verified candidate identity under the approved privacy notice.',['Privacy notice'=>'Explains the current collection purpose.','Account fields'=>'Collects only email and a strong password.','Verification step'=>'Proves ownership before account use.'],['Read the notice','Create account','Verify email ownership'],['register','create account','verification','privacy']],
        'candidate.recover'=>['Recover candidate account','Candidate account','Candidates','Request a time-limited recovery link without revealing whether an account exists.',['Email field'=>'Accepts the account email.','Generic response'=>'Prevents account discovery.','Security guidance'=>'Explains link expiry and safe handling.'],['Enter account email','Submit recovery request','Use the emailed link'],['recovery','forgot password','email']],
        'candidate.reset'=>['Reset candidate password','Candidate account','Candidates','Replace a password using a valid, single-use token.',['Token check'=>'Rejects invalid, expired, or consumed links.','Password rules'=>'Shows the required strength.','Session revocation'=>'Invalidates earlier candidate sessions.'],['Open valid link','Set a strong password','Sign in again'],['reset','password','token','session']],
        'candidate.verify'=>['Verify candidate email','Candidate account','Candidates','Confirm control of the candidate email address.',['Verification token'=>'Single-use proof sent by email.','Account state'=>'Moves the account from pending to active.','Sign-in route'=>'Continues to the candidate workspace.'],['Open verification link','Validate token','Activate account'],['verify','email','activation']],
        'candidate.privacy'=>['Candidate privacy notice','Candidate account','Candidates and privacy reviewers','Understand what is collected, why, and how to exercise privacy rights.',['Purpose summary'=>'Connects each data group to recruitment.','Stage limits'=>'Explains why sensitive data is not requested initially.','Privacy requests'=>'Routes access, correction, deletion, restriction, or objection.'],['Read purposes','Review retention and access','Continue only when understood'],['privacy','retention','rights','personal data']],
        'candidate.dashboard'=>['Candidate home','Candidate journey','Candidates','See current applications and the next action in one place.',['Journey summary'=>'Counts only the candidate’s records.','Recent applications'=>'Shows role and candidate-safe status.','Next action'=>'Points to interviews, offers, or onboarding.'],['Sign in','Review current status','Open the next required item'],['dashboard','status','next action']],
        'candidate.applications'=>['Your applications','Candidate journey','Candidates','Review every role submitted through this account.',['Role list'=>'Keeps each job separate.','Status label'=>'Uses candidate-safe language.','Updated time'=>'Shows when the record last changed.'],['Open Applications','Choose a role','Review its timeline'],['applications','roles','history']],
        'candidate.application'=>['Application details','Candidate journey','Candidates','Confirm the accepted job terms, submitted information, and dated history.',['Job snapshot'=>'Preserves the exact role version accepted.','Application summary'=>'Shows the minimum submitted information.','Timeline'=>'Shows dated candidate-visible changes.'],['Open an application','Review accepted terms','Follow the latest next step'],['application detail','job snapshot','timeline']],
        'candidate.apply'=>['Apply for a role','Candidate journey','Candidates','Save and submit a minimum-data application for one validated published role.',['Selected role'=>'Prevents switching or repeating job selection.','Application fields'=>'Requests only first-stage information.','Privacy acknowledgement'=>'Records the approved notice version.'],['Open Start application','Save the draft','Submit the application'],['apply','draft','submit','job']],
        'candidate.interviews'=>['Interviews','Candidate journey','Candidates','Review interview details and record a confirmation or reschedule request.',['Schedule'=>'Shows UTC time and named timezone.','Location details'=>'Revealed only inside the protected account.','Response controls'=>'Records confirm or reschedule state.'],['Open Interviews','Review time and location','Record your response'],['interview','schedule','timezone','reschedule']],
        'candidate.offers'=>['Offers','Candidate journey','Candidates','Review the exact approved offer version before accepting or declining.',['Version and hash'=>'Identify the immutable approved terms.','Expiry'=>'Shows the response deadline.','Response receipt'=>'Records the candidate decision and time.'],['Open Offers','Review the complete version','Accept or decline'],['offer','accept','decline','expiry']],
        'candidate.onboarding'=>['Onboarding','Candidate journey','Candidates','Complete only applicable pre-employment tasks and understand why each is needed.',['Task purpose'=>'Explains why the item is required.','Visibility'=>'States who can review it.','Dependency and due date'=>'Shows ordering and timing.'],['Open Onboarding','Complete available prerequisites','Submit the item for review'],['onboarding','tasks','requirements','due date']],
        'candidate.documents'=>['Documents','Candidate journey','Candidates','Respond securely to an approved document request and track scan and review state.',['Request purpose'=>'Explains why the file is needed.','Security state'=>'Shows quarantine, scan, and review.','Approved download'=>'Releases only clean, approved files.'],['Open an approved request','Upload PDF, JPG, or PNG','Wait for clean review'],['document','upload','scan','quarantine']],
        'candidate.messages'=>['Messages','Candidate journey','Candidates','Read secure recruitment messages and contact the recruitment team.',['Conversation history'=>'Shows messages for this candidate only.','Related application'=>'Keeps questions in context.','Send a message'=>'Stores encrypted support content.'],['Open Messages','Choose the related application','Send the question'],['messages','support','contact recruiter']],
        'candidate.settings'=>['Privacy and settings','Candidate journey','Candidates','Control optional notifications and submit a privacy request.',['Notification preferences'=>'Controls optional interview and onboarding email.','Required messages'=>'Keeps security and offer notices enabled.','Privacy request'=>'Creates a tracked rights request.'],['Open Settings','Choose a preference or request','Confirm the saved result'],['settings','notifications','privacy request']],
        'staff.requisitions'=>['Requisition queue','Staff operations','Recruitment, HR, hiring approvers','Create an accountable request and obtain independent approval before publishing.',['Queue'=>'Shows owner, headcount, target, and status.','Approval evidence'=>'Records actor, reason, and time.','Release callout'=>'Shows whether mutations are available.'],['Prepare requisition','Submit for approval','Independent approver decides'],['requisition','headcount','approval','owner']],
        'staff.jobs'=>['Job publication','Staff operations','Recruitment and HR','Publish candidate-safe content only from an approved requisition.',['Job version'=>'Tracks every content revision.','Publication window'=>'Controls opening, pause, close, and expiry.','Public projection'=>'Sends only approved fields to the website.'],['Create job draft','Review and publish','Verify public projection'],['job','publish','version','careers']],
        'staff.pipeline'=>['Candidate pipeline','Staff operations','Recruitment and hiring teams','Move authorized applications through controlled stages with candidate-safe updates.',['Application reference'=>'Identifies one candidate-role record.','Stage age'=>'Highlights work awaiting action.','Ownership'=>'Limits work to assigned scope.'],['Open assigned application','Record evidence and decision','Confirm timeline update'],['pipeline','application','stage','assignment']],
        'staff.candidate'=>['Candidate case','Staff operations','Authorized Recruitment and HR staff','Review one scoped candidate record and complete the next authorized action.',['Authorized summary'=>'Shows protected contact and application data.','Evidence sections'=>'Groups timeline, interviews, offers, onboarding, and documents.','PII audit'=>'Records access to protected fields.'],['Open the assigned case','Review relevant evidence','Perform only the authorized action'],['candidate case','pii','audit','application']],
        'staff.interviews'=>['Interview desk','Staff operations','Recruiters, coordinators, and panel members','Schedule interviews and collect independent structured scorecards.',['Schedule queue'=>'Shows time and timezone.','Participants'=>'Records panel role and responsibility.','Scorecard'=>'Locks submitted ratings to approved criteria.'],['Schedule interview','Candidate responds','Panel submits scorecard'],['interview desk','panel','scorecard']],
        'staff.offers'=>['Offer center','Staff operations','Recruitment and HR approvers','Prepare, independently approve, and deliver an immutable offer.',['Offer status'=>'Shows draft through final response.','Version history'=>'Preserves superseded terms.','Approval evidence'=>'Separates preparer and approver.'],['Prepare offer version','Independent approval','Deliver and await response'],['offers','maker checker','version','delivery']],
        'staff.onboarding'=>['Onboarding cases','Staff operations','HR and onboarding owners','Run approved task templates and prepare independently reviewed readiness.',['Case owner'=>'Names the accountable coordinator.','Task dependencies'=>'Prevent work from bypassing prerequisites.','Readiness controls'=>'Separate preparation from approval.'],['Start approved template','Resolve every required item','Approve readiness independently'],['onboarding case','template','readiness','dependencies']],
        'staff.exceptions'=>['Exception desk','Staff operations','Recruitment and HR owners','Find aging, blocked, rejected, expired, or failed work that needs ownership.',['Exception type'=>'Explains the condition.','Record reference'=>'Links the issue to its source record.','Owner and age'=>'Makes follow-up accountable.'],['Review exception','Investigate source evidence','Resolve through the owning workflow'],['exceptions','aging','blocked','failed']],
        'staff.conversions'=>['Employee conversion','Staff operations','HRIS preparers and independent approvers','Create one minimal employee record after accepted offer and approved readiness.',['Payload hash'=>'Proves the reviewed employee fields.','Duplicate evidence'=>'Checks payroll ID, email, identity, and government identifiers.','Reconciliation'=>'Compares the created employee snapshot to the approved payload.'],['Prepare minimum payload','Run duplicate check and approval','Create and reconcile employee'],['employee conversion','duplicate','reconcile','maker checker']],
        'staff.reports'=>['Operations snapshot','Staff operations','Recruitment and HR leaders','Review system-derived workload totals without invented targets.',['Workload totals'=>'Counts authoritative records.','Snapshot time'=>'States when figures were generated.','Exception link'=>'Routes action back to source records.'],['Open Reports','Review current totals','Investigate in the owning queue'],['reports','metrics','workload','snapshot']],
        'staff.access'=>['Recruitment access','Administration','Authorized administrators','Grant and revoke explicit, scoped, expiring recruitment capabilities.',['Capability catalogue'=>'Lists every known permission.','Scope'=>'Limits access globally or to a record domain.','Grant evidence'=>'Stores grantor, reason, expiry, and revocation.'],['Confirm approved access request','Grant the minimum capability','Review or revoke access'],['access','capability','least privilege','revoke']],
    ];
    $manifest=[];
    foreach($definitions as $id=>$d){
        $manifest[$id]=['id'=>$id,'label'=>$d[0],'group'=>$d[1],'availability'=>'Disconnected','summary'=>$d[3],'purpose'=>$d[3],'audience'=>$d[2],'successOutcome'=>$d[3],'beforeYouStart'=>['Confirm the page is available for your role.','Check the release-state notice before expecting data to save or change.'],'landmarks'=>array_map(static fn($title,$description)=>['title'=>$title,'description'=>$description],array_keys($d[4]),array_values($d[4])),'actions'=>[['title'=>'Follow the qualified workflow','outcome'=>$d[3],'steps'=>array_map(static fn($step)=>$step.' when the release-state notice says the workflow is available.',$d[5]),'guardrail'=>'Foundation mode is disconnected: controls remain disabled and no recruitment data is changed.']],'flow'=>['title'=>$d[0].' flow','description'=>'The governed sequence for this page.','steps'=>array_map(static fn($step)=>['label'=>$step,'detail'=>'Complete this step only when its prerequisite and permission are satisfied.'],$d[5])],'governance'=>['Foundation mode is disconnected and does not authorize collection or mutation.','Consequential decisions retain an actor, time, reason, and audit evidence.'],'keywords'=>$d[6]];
    }
    return $manifest;
}
