<?php
declare(strict_types=1);
require_once __DIR__.'/../recruitment/includes/feature.php';
require_once __DIR__.'/../recruitment/includes/guide_manifest.php';
$failures=[];$check=static function(bool $condition,string $message)use(&$failures):void{if(!$condition){$failures[]=$message;echo "FAIL: {$message}\n";}else echo "PASS: {$message}\n";};
$manifest=recruitment_guide_manifest();
$expected=['overview','candidate.sign-in','candidate.register','candidate.recover','candidate.reset','candidate.verify','candidate.privacy','candidate.dashboard','candidate.applications','candidate.application','candidate.apply','candidate.interviews','candidate.offers','candidate.onboarding','candidate.documents','candidate.messages','candidate.settings','staff.requisitions','staff.jobs','staff.pipeline','staff.candidate','staff.interviews','staff.offers','staff.onboarding','staff.exceptions','staff.conversions','staff.reports','staff.access'];
$ids=array_keys($manifest);sort($ids);$sortedExpected=$expected;sort($sortedExpected);$check($ids===$sortedExpected,'guide manifest covers every recruitment page exactly once');
foreach($manifest as $id=>$guide){$check(($guide['id']??'')===$id,"{$id} has a stable ID");foreach(['label','group','availability','summary','purpose','audience','successOutcome'] as $field)$check(trim((string)($guide[$field]??''))!=='' ,"{$id} has {$field}");$check(count($guide['landmarks']??[])>=3,"{$id} has at least three landmarks");$check(count($guide['flow']['steps']??[])>=3,"{$id} has an explanatory process flow");$check(count($guide['actions']??[])>=1,"{$id} states the available or qualified action");foreach($guide['actions']??[] as $action){$check(count($action['steps']??[])>=3,"{$id} action has at least three steps");$check(str_contains((string)($action['guardrail']??''),'Foundation mode'),"{$id} action states the disconnected guardrail");}}
$root=realpath(__DIR__.'/..');$component=(string)file_get_contents($root.'/recruitment/includes/guide_component.php');$js=(string)file_get_contents($root.'/recruitment/assets/guide.js');$css=(string)file_get_contents($root.'/recruitment/assets/guide.css');$publicGuideRedirect=(string)file_get_contents($root.'/recruitment/guide.php');
$check(str_contains($component,'Open guide for'),'context launcher has a page-specific accessible name');$check(str_contains($component,'role="dialog"')&&str_contains($component,'aria-modal="true"'),'guide uses an accessible modal dialog');$check(str_contains($js,"event.key==='Escape'")&&str_contains($js,'returnFocus.focus'),'guide closes with Escape and returns focus');$check(str_contains($js,"event.key!=='Tab'")&&str_contains($js,'preventDefault'),'guide traps keyboard focus');$check(str_contains($js,'searchable(g)'),'guide search indexes complete article content');$check((bool)preg_match('/@media\s*\(\s*max-width\s*:\s*760px\s*\)/',$css),'guide has a mobile layout');$check(str_contains($css,'prefers-reduced-motion'),'guide respects reduced motion');
$check(str_contains($publicGuideRedirect,'https://taascor.com/recruitment/guide/'),'HRIS Guide Center redirects to the canonical public guide');
foreach(['staff/workspace-page.php','staff/candidate.php','staff/admin/access.php','index.php'] as $path)$check(str_contains((string)file_get_contents($root.'/recruitment/'.$path),'recruitment_guide_render'),'context guide is integrated into '.$path);
if($failures!==[]){fwrite(STDERR,"RESULT: ".count($failures)." guide check(s) failed.\n");exit(1);}echo "RESULT: Recruitment Guide Center checks passed.\n";
